{{- if .Values.service.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "bip39.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
{{- if .Values.service.certificate.on_ingress }}
    certmanager.k8s.io/cluster-issuer: {{ .Values.service.certificate.issuer }}
    certmanager.k8s.io/acme-challenge-type: http01
{{- end }}
spec:
{{- if .Values.service.certificate.enabled }}
  tls:
    - hosts:
        - {{ .Values.service.external_dns }}
      secretName: {{ template "bip39.fullname" . }}-tls
{{- end }}

  rules:
  - host: {{ .Values.service.external_dns }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "bip39.fullname" . }}
          servicePort: {{ .Values.service.ingress_port }}
{{- end }}
