apiVersion: v1
kind: Service
metadata:
  name: {{ template "bip39.fullname" . }}
  labels:
    app: {{ template "bip39.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.ingress_port }}
    targetPort: "http"
    protocol: "TCP"
    name: http
  selector:
    app: {{ template "bip39.fullname" . }}
    release: "{{ .Release.Name }}"
